//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebApps.Assets.Pages.projects.COMP235.L1_GET_POST_COOKIE.Part3
{


    public partial class LandingPage
    {
    }
}
